# Generated by Django 3.1.5 on 2022-04-11 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0003_author_lastdrawing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='lastDrawing',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
