# Generated by Django 3.1.5 on 2022-04-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0004_auto_20220411_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawingmodel',
            name='points',
            field=models.TextField(null=True),
        ),
    ]
